### ISSUE TITLE
[openqa-revtui] Filter investigate and test jobs

### ISSUE THREAD

**Issue by grisu48** [os-autoinst/openqa-mon#135]
In the current configuration, investigate jobs spawned by `geekotest` or test jobs by `clone-custom-git-refspec` are displayed in some job groups, e.g. in `opensuse-microos.toml` because we're only selecting based on flavor.

We must not show results from `_GROUP=0`. I'm not sure if they should be returned by the openQA API or if we have to filter them out afterwards.

**Comment by grisu48** [comment]
Raised the topic in https://suse.slack.com/archives/C02CANHLANP/p1707404568507239

**Comment by grisu48** [comment]
Looks like this is by design and we need to filter those results out in `openqa-revtui`.

**Comment by grisu48** [comment]
I cannot find a way to filter out jobs from cloned or investigated jobs, as the job group id is not provided to jobs.

We opened https://progress.opensuse.org/issues/155398 to allow for such feature.

**Comment by grisu48** [comment]
Closing as duplicate of https://github.com/grisu48/openqa-mon/issues/76

**Comment by okurz** [comment]
> Closing as duplicate of https://github.com/grisu48/openqa-mon/issues/76

By now that's https://github.com/os-autoinst/openqa-mon/issues/76
