### ISSUE TITLE
github.com/streadway/amqp  is deprecated

### ISSUE THREAD

**Issue by asmorodskyi** [os-autoinst/openqa-mon#148]
make requirements                                                                                                                                 [10:24:31]
go get ./...
go: downloading github.com/grisu48/gopenqa v0.7.3
go: downloading golang.org/x/crypto v0.21.0
go: downloading github.com/streadway/amqp v1.1.0
go: downloading github.com/BurntSushi/toml v1.3.2
go: downloading golang.org/x/term v0.18.0
go: downloading golang.org/x/sys v0.18.0
go: module github.com/streadway/amqp is deprecated: Consider using the github.com/rabbitmq/amqp091-go package instead.

**Comment by grisu48** [comment]
I need to check if the suggested package works in the same way.

**Comment by grisu48** [comment]
In the meantime: https://github.com/grisu48/openqa-mon/pull/149

**Comment by grisu48** [comment]
Fixed in https://github.com/grisu48/openqa-mon/pull/150

**Comment by grisu48** [comment]
Updated in https://github.com/grisu48/openqa-mon/releases/tag/v1.2.2
