### ISSUE TITLE
Consider a generic implementation of Unique() func

### ISSUE THREAD

**Issue by ilmanzo** [os-autoinst/openqa-mon#175]
with reference to: 

https://github.com/os-autoinst/openqa-mon/blob/900c7149e563b8ea972d59f22e520ea0d513a46e/cmd/openqa-mon/util.go#L44

and 
https://github.com/os-autoinst/openqa-mon/blob/900c7149e563b8ea972d59f22e520ea0d513a46e/cmd/openqa-mon/util.go#L56

a sample implementation with generics types (introduced in Go 1.18) that also avoids allocating a map of bools:

```go
func unique[T comparable](slice []T) []T {
    seen := make(map[T]struct{})
    unique := []T{}

    for _, item := range slice {
        if _, exists := seen[item]; !exists {
            seen[item] = struct{}{}
            unique = append(unique, item)
        }
    }

    return unique
}
```

to call it:

```go
uniqueInts := unique([]int{1, 2, 2, 3, 4, 4, 5})
uniqueStrings := unique([]string{"apple", "banana", "apple", "cherry"})
uniqueFloat64s := unique([]float64{1.1, 2.2, 2.2, 3.3, 4.4})
```

**Comment by ilmanzo** [comment]
Opening this issue only to have your opinion, if you like the idea I will follow up with a Pull Request :)

**Comment by grisu48** [comment]
This would be a great refactoring idea. I think the code still originates from the pre-generics time, or at least when we used a go version that didn't had generics.

Feel free to open a PR :slightly_smiling_face:

**Comment by grisu48** [comment]
Solved in https://github.com/os-autoinst/openqa-mon/pull/176 - Thank you!
