### ISSUE TITLE
Build complete dependency tree

### ISSUE THREAD

**Issue by pdostal** [os-autoinst/openqa-mon#20]
Hello Felix,

see this example:
```bash
$ openqa-mon -mfpc 2 http://openqa/t10950 http://openqa/tests/10926
```
![Screenshot 2020-07-14 at 09 33 07](https://user-images.githubusercontent.com/1254493/87398617-69532d80-c5b6-11ea-992a-8e6a0e982f6c.png)
And notice that:
 * The `qam-kvm-virtmanager` is listed multiple times as I restarted it.
 * The `qam-kvm-snapshots` is missing completely even tho it exists.

I like the project more and more!
Thank you for your amazing work!

**Comment by grisu48** [comment]
Thanks for filing the bug. Seems the child jobs are not following atm, I can reproduce this locally as well
![no-follow](https://user-images.githubusercontent.com/1527829/87400836-9fde7780-c5b9-11ea-873b-584d297e9be8.png)

**Comment by grisu48** [comment]
The first bug is fixed in https://github.com/grisu48/openqa-mon/pull/21 (Child jobs are now also followed)

The second issue is that currently we fetch only jobs to depth 1 and I need to come up with a clever way of representing job dependency trees. So this is going to remain open for some more time

**Comment by pdostal** [comment]
Confirmed 👍

**Comment by grisu48** [comment]
Renaming the issue because it has become only about the second issue: Building a complete dependency tree instead of just showing the direct children

**Comment by grisu48** [comment]
@pdostal is this issue still present? IMHO in the latest version the display of the child jobs is appropriate and we can close this issue.

**Comment by pdostal** [comment]
Probably so. I have latest version so I can reopen this if needed.
