### ISSUE TITLE
openqa-mon does not use default DefaultRemote

### ISSUE THREAD

**Issue by d3flex** [os-autoinst/openqa-mon#35]
Based on the README using `~/.openqa-mon.conf`, openqa-mon should use the DefaultRmote

```
## Default remote to use, if nothing is defined                                                                                                                                                                                              
# DefaultRemote = http://openqa.opensuse.org 
```
But it fails, requiring the parameter, even if you uncomment the line in the .openqa-mon.conf

expected:
if you dont define anything it should use the default remote ex openqa-mon -j 1675915 should show https://openqa.opensuse.org/tests/1675915

**Comment by d3flex** [comment]
https://github.com/grisu48/openqa-mon/pull/36

**Comment by grisu48** [comment]
Fixed in https://github.com/grisu48/openqa-mon/pull/36
