### ISSUE TITLE
Wait for all jobs to be done and return aggregated job result in exit code

### ISSUE THREAD

**Issue by okurz** [os-autoinst/openqa-mon#39]
## Motivation
For openQA verification jobs a user as well as a CI system would want to wait for completion off a list of openQA jobs and represent the result, e.g. by exit code

## Acceptance criteria
* **AC1:** openqa-mon can be started to monitor all specified jobs until they are done and exits with exit code resembling the aggregated job status
* **AC2:** openqa-mon started with a list of all passed openQA jobs returns exit code 0
* **AC3:** openqa-mon started with a list of multiple passed and at least one failed openQA job returns non-zero exit code
* **AC4:** Same as AC3 but multiple passed and at least one incomplete job

## Suggestions
monitor until all selected jobs are done and then exit with the exit code being non-zero if any job failed? that would be a good mode for verification runs where one wants to have jobs non-failed

**Comment by grisu48** [comment]
This issue is addressed in https://github.com/grisu48/openqa-mon/pull/41, I'm gonna bring it to OBS today.

**Comment by okurz** [comment]
awesome :) I will check how it behaves then

**Comment by grisu48** [comment]
Merged and published via [OBS](https://software.opensuse.org/package/openqa-mon)

**Comment by okurz** [comment]
Running against at least one incomplete job seems to return zero when it should be non-zero. I tried with `openqa-mon --continuous 10 --exit --follow https://openqa.opensuse.org/t3088419`

**Comment by grisu48** [comment]
Thanks for reopening. Will have a look
