### ISSUE TITLE
Detect restarted jobs

### ISSUE THREAD

**Issue by grisu48** [os-autoinst/openqa-mon#7]
Would be nice, if restarted jobs get refreshed automatically to the new run.

**Comment by grisu48** [comment]
The job property `"clone_id"` should be useful in this case

    {
      "job": {
        "assets": {
        ...
        "clone_id": 1056,
        ...
        "result": "failed",
        },
        "state": "done",
        ...
      }
    }

**Comment by pdostal** [comment]
Btw. Felix if you will be following restarted jobs you can follow parent / paralel jobs as well.

**Comment by grisu48** [comment]
Good remark, indeed I will need to look into that!

**Comment by grisu48** [comment]
Added in 0150403 by passing the `-f` or `--follow` program argument
