### ISSUE TITLE
[openqa-mon] Some entries are shown multiple times

### ISSUE THREAD

**Issue by pdostal** [os-autoinst/openqa-mon#71]
Please see the job IDs on the screenshot:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1254493/180581514-d3e91f3e-b42c-4607-b553-f5b65574c004.png">

**Comment by grisu48** [comment]
I think this bug has been resolved in the meantime. Can we close the issue?

**Comment by pdostal** [comment]
Yes, of course.

**Comment by grisu48** [comment]
Thank you!
