### ISSUE TITLE
Create container

### ISSUE THREAD

**Issue by grisu48** [os-autoinst/openqa-mon#79]
Since nowadays everything is in containers, why not also create a container for this little fella?

**Comment by grisu48** [comment]
I realize myself that this is unnecessary and close the issue.

Reason: This is a single-binary CLI tool. This does not need to go into a container.

**Comment by okurz** [comment]
Actually OBS is already building a container from the Tumbleweed package in my home repo. Use

```
podman run --rm -it registry.opensuse.org/home/okurz/container/containers/tumbleweed:curl-openqa-mon openqa-mon
```

to run openqa-mon from container.

**Comment by grisu48** [comment]
Thank you!
