### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by grisu48** [os-autoinst/openqa-mon#8]
The number of configuration parameters increases. Perhaps a config file with per-host defaults makes sense now. Something like

    defaultRemote = https://openqa.opensuse.org
    
    [openqa.opensuse.org]
    continuous=5
    bell=1
    notify=0
    
    [openqa.my-instance]
    continuous=1
    bell=1
    notify=1
    follow=1

**Comment by grisu48** [comment]
Request from @dzedro to include a default remote as well.

**Comment by dzedro** [comment]
That would be good, I would not need to always write REMOTE.

**Comment by grisu48** [comment]
Implemented in 92f22cafa643f0630ff39b67e79f535ea7f6f53a
